spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_blog_springcode
    username: root
    password: springroot
app:
  jwt-expiration-milliseconds: 604800000
  jwt-secret: JWTSecretKey